### PR TITLE
Adds urls for CodeClimate and CircleCI

### PR DESCRIPTION
**Pull request by ajkamel**
This commit updates the project for easy to read passing or failing
builds.  It also adds the project description in respect to it being a
group project.

### CODE REVIEW

**Comment by ajkamel** [comment]
@samnang should be good to merge now.

**Comment by samnang** [comment]
Thank @ajkamel, Look good :+1:

**Comment by evan-007** [comment]
:+1: what was the issue with spring? we just never installed the binstubs for it?

**Comment by samnang** [comment]
@evan-007 right, the changes are because of generating binstubs, but it's not the issue. The commit is about adding badge of CI and CodeClimate, but the change of binstubs here as well, so that's why we want to exclude the changes from binstubs in another commit.

**Comment by ajkamel** [comment]
@evan-007 you mentioned merging the pull request through command line v. through github.  Could you explain or link to a source for the process?

**Comment by evan-007** [comment]
yeah, that was my reference.

I just put this in my `.gitconfig` to stop merge commits. It's in the thoughtbot dotfiles

```
[merge]
  ff = only
```

Then it's pretty much just follow the guide. The only thing to remember is to push to the remote branch after rebasing from master or else github won't automatically close your pr.

**Comment by evan-007** [comment]
I just merged my other pr, here's how i did it, `g` is an alias for `git`:

```
cover master % g checkout homepage_header
Switched to branch 'homepage_header'

cover homepage_header % g rebase master
First, rewinding head to replay your work on top of it...
Applying: Add nav header and set root_path

cover homepage_header % g push
To git@github.com:ajkamel/cover.git
 ! [rejected]        homepage_header -> homepage_header (non-fast-forward)
error: failed to push some refs to 'git@github.com:ajkamel/cover.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

cover homepage_header % g push -f
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 584 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
To git@github.com:ajkamel/cover.git
 + afcc2fb...29ad157 homepage_header -> homepage_header (forced update)

cover homepage_header % g checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

cover master % g merge homepage_header
Updating 870af75..29ad157
Fast-forward
 app/assets/javascripts/refills/centered_navigation.js    |  13 ++
 app/assets/stylesheets/application.css.scss              |   1 +
 app/assets/stylesheets/refills/_centered-navigation.scss | 267 +++++++++++++++++++++++++++++++++
 app/views/layouts/_user_menu.html.erb                    |   6 +
 app/views/layouts/application.html.erb                   |   1 +
 app/views/pages/home.html.erb                            |   0
 app/views/refills/_centered_navigation.html.erb          |  21 +++
 config/initializers/high_voltage.rb                      |   3 +
 8 files changed, 312 insertions(+)
 create mode 100644 app/assets/javascripts/refills/centered_navigation.js
 create mode 100644 app/assets/stylesheets/refills/_centered-navigation.scss
 create mode 100644 app/views/layouts/_user_menu.html.erb
 create mode 100644 app/views/pages/home.html.erb
 create mode 100644 app/views/refills/_centered_navigation.html.erb
 create mode 100644 config/initializers/high_voltage.rb

cover master % g push
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:ajkamel/cover.git
   870af75..29ad157  master -> master

cover master % g push origin :homepage_header
To git@github.com:ajkamel/cover.git
 - [deleted]         homepage_header
cover master %
```

**Comment by samnang** [comment]
@ajkamel @evan-007 there are two options when you want to merge pull request into master with no fast forward.

1. Github merge button
2. Run commands on your locals. if you don't know how, you can see the below screenshot:

cover 2015-11-07 16-26-09

**Pull request merged**
